[[accerionbindings]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a270e07948e1d7dd4cd80cfa471c01b4e995d03c"
libc = "glibc"
os = "linux"

    [[accerionbindings.download]]
    sha256 = "393fafe98a6cb7d36223fbf406a398f620e6c2eaea0ee17ac14cce93ccb36aec"
    url = "https://github.com/jordy-van-appeven/accerionbindings_jll.jl/releases/download/accerionbindings-v5.4.2+0/accerionbindings.v5.4.2.x86_64-linux-gnu-cxx11.tar.gz"
